# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helloworld.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='helloworld.proto',
  package='helloworld',
  syntax='proto3',
  serialized_pb=_b('\n\x10helloworld.proto\x12\nhelloworld\"\x1f\n\x0f\x43\x61tegoryRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\" \n\rCategoryReply\x12\x0f\n\x07message\x18\x01 \x01(\t\" \n\x10MakeModelRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"!\n\x0eMakeModelReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t2\x9d\x02\n\x07Greeter\x12>\n\x08SayHello\x12\x18.helloworld.HelloRequest\x1a\x16.helloworld.HelloReply\"\x00\x12\x43\n\rSayHelloAgain\x12\x18.helloworld.HelloRequest\x1a\x16.helloworld.HelloReply\"\x00\x12\x44\n\x08\x43\x61tegory\x12\x1b.helloworld.CategoryRequest\x1a\x19.helloworld.CategoryReply\"\x00\x12G\n\tMakeModel\x12\x1c.helloworld.MakeModelRequest\x1a\x1a.helloworld.MakeModelReply\"\x00\x42\x36\n\x1bio.grpc.examples.helloworldB\x0fHelloWorldProtoP\x01\xa2\x02\x03HLWb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CATEGORYREQUEST = _descriptor.Descriptor(
  name='CategoryRequest',
  full_name='helloworld.CategoryRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='helloworld.CategoryRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=63,
)


_CATEGORYREPLY = _descriptor.Descriptor(
  name='CategoryReply',
  full_name='helloworld.CategoryReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='helloworld.CategoryReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=97,
)


_MAKEMODELREQUEST = _descriptor.Descriptor(
  name='MakeModelRequest',
  full_name='helloworld.MakeModelRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='helloworld.MakeModelRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=131,
)


_MAKEMODELREPLY = _descriptor.Descriptor(
  name='MakeModelReply',
  full_name='helloworld.MakeModelReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='helloworld.MakeModelReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=133,
  serialized_end=166,
)


_HELLOREQUEST = _descriptor.Descriptor(
  name='HelloRequest',
  full_name='helloworld.HelloRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='helloworld.HelloRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=168,
  serialized_end=196,
)


_HELLOREPLY = _descriptor.Descriptor(
  name='HelloReply',
  full_name='helloworld.HelloReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='helloworld.HelloReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=198,
  serialized_end=227,
)

DESCRIPTOR.message_types_by_name['CategoryRequest'] = _CATEGORYREQUEST
DESCRIPTOR.message_types_by_name['CategoryReply'] = _CATEGORYREPLY
DESCRIPTOR.message_types_by_name['MakeModelRequest'] = _MAKEMODELREQUEST
DESCRIPTOR.message_types_by_name['MakeModelReply'] = _MAKEMODELREPLY
DESCRIPTOR.message_types_by_name['HelloRequest'] = _HELLOREQUEST
DESCRIPTOR.message_types_by_name['HelloReply'] = _HELLOREPLY

CategoryRequest = _reflection.GeneratedProtocolMessageType('CategoryRequest', (_message.Message,), dict(
  DESCRIPTOR = _CATEGORYREQUEST,
  __module__ = 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.CategoryRequest)
  ))
_sym_db.RegisterMessage(CategoryRequest)

CategoryReply = _reflection.GeneratedProtocolMessageType('CategoryReply', (_message.Message,), dict(
  DESCRIPTOR = _CATEGORYREPLY,
  __module__ = 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.CategoryReply)
  ))
_sym_db.RegisterMessage(CategoryReply)

MakeModelRequest = _reflection.GeneratedProtocolMessageType('MakeModelRequest', (_message.Message,), dict(
  DESCRIPTOR = _MAKEMODELREQUEST,
  __module__ = 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.MakeModelRequest)
  ))
_sym_db.RegisterMessage(MakeModelRequest)

MakeModelReply = _reflection.GeneratedProtocolMessageType('MakeModelReply', (_message.Message,), dict(
  DESCRIPTOR = _MAKEMODELREPLY,
  __module__ = 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.MakeModelReply)
  ))
_sym_db.RegisterMessage(MakeModelReply)

HelloRequest = _reflection.GeneratedProtocolMessageType('HelloRequest', (_message.Message,), dict(
  DESCRIPTOR = _HELLOREQUEST,
  __module__ = 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.HelloRequest)
  ))
_sym_db.RegisterMessage(HelloRequest)

HelloReply = _reflection.GeneratedProtocolMessageType('HelloReply', (_message.Message,), dict(
  DESCRIPTOR = _HELLOREPLY,
  __module__ = 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.HelloReply)
  ))
_sym_db.RegisterMessage(HelloReply)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\033io.grpc.examples.helloworldB\017HelloWorldProtoP\001\242\002\003HLW'))
try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces


  class GreeterStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.SayHello = channel.unary_unary(
          '/helloworld.Greeter/SayHello',
          request_serializer=HelloRequest.SerializeToString,
          response_deserializer=HelloReply.FromString,
          )
      self.SayHelloAgain = channel.unary_unary(
          '/helloworld.Greeter/SayHelloAgain',
          request_serializer=HelloRequest.SerializeToString,
          response_deserializer=HelloReply.FromString,
          )
      self.Category = channel.unary_unary(
          '/helloworld.Greeter/Category',
          request_serializer=CategoryRequest.SerializeToString,
          response_deserializer=CategoryReply.FromString,
          )
      self.MakeModel = channel.unary_unary(
          '/helloworld.Greeter/MakeModel',
          request_serializer=MakeModelRequest.SerializeToString,
          response_deserializer=MakeModelReply.FromString,
          )


  class GreeterServicer(object):
    """The greeting service definition.
    """

    def SayHello(self, request, context):
      """Sends a greeting
      """
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def SayHelloAgain(self, request, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def Category(self, request, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def MakeModel(self, request, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_GreeterServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'SayHello': grpc.unary_unary_rpc_method_handler(
            servicer.SayHello,
            request_deserializer=HelloRequest.FromString,
            response_serializer=HelloReply.SerializeToString,
        ),
        'SayHelloAgain': grpc.unary_unary_rpc_method_handler(
            servicer.SayHelloAgain,
            request_deserializer=HelloRequest.FromString,
            response_serializer=HelloReply.SerializeToString,
        ),
        'Category': grpc.unary_unary_rpc_method_handler(
            servicer.Category,
            request_deserializer=CategoryRequest.FromString,
            response_serializer=CategoryReply.SerializeToString,
        ),
        'MakeModel': grpc.unary_unary_rpc_method_handler(
            servicer.MakeModel,
            request_deserializer=MakeModelRequest.FromString,
            response_serializer=MakeModelReply.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'helloworld.Greeter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaGreeterServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    """The greeting service definition.
    """
    def SayHello(self, request, context):
      """Sends a greeting
      """
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def SayHelloAgain(self, request, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def Category(self, request, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def MakeModel(self, request, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaGreeterStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    """The greeting service definition.
    """
    def SayHello(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      """Sends a greeting
      """
      raise NotImplementedError()
    SayHello.future = None
    def SayHelloAgain(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()
    SayHelloAgain.future = None
    def Category(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()
    Category.future = None
    def MakeModel(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()
    MakeModel.future = None


  def beta_create_Greeter_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('helloworld.Greeter', 'Category'): CategoryRequest.FromString,
      ('helloworld.Greeter', 'MakeModel'): MakeModelRequest.FromString,
      ('helloworld.Greeter', 'SayHello'): HelloRequest.FromString,
      ('helloworld.Greeter', 'SayHelloAgain'): HelloRequest.FromString,
    }
    response_serializers = {
      ('helloworld.Greeter', 'Category'): CategoryReply.SerializeToString,
      ('helloworld.Greeter', 'MakeModel'): MakeModelReply.SerializeToString,
      ('helloworld.Greeter', 'SayHello'): HelloReply.SerializeToString,
      ('helloworld.Greeter', 'SayHelloAgain'): HelloReply.SerializeToString,
    }
    method_implementations = {
      ('helloworld.Greeter', 'Category'): face_utilities.unary_unary_inline(servicer.Category),
      ('helloworld.Greeter', 'MakeModel'): face_utilities.unary_unary_inline(servicer.MakeModel),
      ('helloworld.Greeter', 'SayHello'): face_utilities.unary_unary_inline(servicer.SayHello),
      ('helloworld.Greeter', 'SayHelloAgain'): face_utilities.unary_unary_inline(servicer.SayHelloAgain),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_Greeter_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('helloworld.Greeter', 'Category'): CategoryRequest.SerializeToString,
      ('helloworld.Greeter', 'MakeModel'): MakeModelRequest.SerializeToString,
      ('helloworld.Greeter', 'SayHello'): HelloRequest.SerializeToString,
      ('helloworld.Greeter', 'SayHelloAgain'): HelloRequest.SerializeToString,
    }
    response_deserializers = {
      ('helloworld.Greeter', 'Category'): CategoryReply.FromString,
      ('helloworld.Greeter', 'MakeModel'): MakeModelReply.FromString,
      ('helloworld.Greeter', 'SayHello'): HelloReply.FromString,
      ('helloworld.Greeter', 'SayHelloAgain'): HelloReply.FromString,
    }
    cardinalities = {
      'Category': cardinality.Cardinality.UNARY_UNARY,
      'MakeModel': cardinality.Cardinality.UNARY_UNARY,
      'SayHello': cardinality.Cardinality.UNARY_UNARY,
      'SayHelloAgain': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'helloworld.Greeter', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
